{{- if .Values.image.pullCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullCredentials.secretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}