{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-history-server.serviceAccountName" . }}
  labels:
    {{- include "spark-history-server.labels" . | nindent 4 }}
  {{- $isS3WithIrsa := and (eq .Values.logStore.type "s3") .Values.logStore.s3.irsaRoleArn }}
  {{- if or .Values.serviceAccount.annotations $isS3WithIrsa }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $isS3WithIrsa }}
    eks.amazonaws.com/role-arn: {{ .Values.logStore.s3.irsaRoleArn }}
    {{- end }}
  {{- end }}
{{- end }}
