{{- if and .Values.historyServer.store.hybridStore.enabled}}
apiVersion: {{ template "spark-history-server.deployment.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ template "spark-history-server.fullname" . }}
  labels:
    {{- include "spark-history-server.labels" . | nindent 4 }}
spec:
  serviceName: {{ template "spark-history-server.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spark-history-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "spark-history-server.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if or .Values.image.pullSecrets (gt (len .Values.image.pullSecrets) 0) .Values.image.pullCredentials.enabled }}
      imagePullSecrets:
        {{- with .Values.image.pullSecrets }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.image.pullCredentials.enabled }}
        {{- with .Values.image.pullCredentials }}
        - name: {{ .secretName }}
        {{- end }}
        {{- end }}
      {{- end }}

      serviceAccountName: {{ include "spark-history-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "spark-history-server.fullname" . }}
        - name: spark-logs
          emptyDir: { }
        - name: tmp-dir
          emptyDir: { }
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: # Launches Spark history server from a Docker container
            - '/opt/spark/sbin/start-history-server.sh'
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "false"
            - name: SPARK_CONF_DIR
              value: /opt/spark/conf
            - name: TMPDIR
              value: "/tmp"
          volumeMounts:
            - name: config-volume
              mountPath: /opt/spark/conf/spark-defaults.conf
              subPath: spark-defaults.conf
            - name: config-volume
              mountPath: /opt/spark/conf/log4j2.properties
              subPath: log4j2.properties
            - name: spark-logs
              mountPath: /opt/spark/logs
            - name: store-volume
              mountPath: {{ .Values.persistence.mountPath }}
            - name: tmp-dir
              mountPath: /tmp
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: store-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
{{- end }}
